import { Inter } from "next/font/google";
import "./globals.css";
import HeaderBar from "@/components/HeaderBar";
<<<<<<< HEAD
import NavBar from "@/components/NavBar";
=======
import Footer from "@/components/Footer";
>>>>>>> d5aa08cccfe88bf787e314268cc883e8b4431e90

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Digitalpluseit",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico?v=4"],
    apple: ["/apple-touch-icon.png?v=4"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderBar />
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
