import { Inter } from "next/font/google";
import "./globals.css";
import HeaderBar from "@/components/HeaderBar";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Digitalpluseit",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico?v=4"],
    apple: ["/apple-touch-icon.png?v=4"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
<<<<<<< HEAD
        {/* <HeaderBar /> */}
=======
        <HeaderBar />
        <NavBar />
>>>>>>> 18127b20f6574e246550fe223e73becabda6576d
        {children}
        <Footer />
      </body>
    </html>
  );
}
