import { Inter } from "next/font/google";
import "./globals.css";
import HeaderBar from "@/components/HeaderBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Digitalpluseit",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico?v=4"],
    apple: ["/apple-touch-icon.png?v=4"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderBar />
        {children}
      </body>
    </html>
  );
}
